CockQuartz.Admin/Controllers/JobManagementController.cs
using System.Web.Mvc;
using CockQuartz.Core;
using CockQuartz.Core.Infrastructure;
using CockQuartz.Core.JobManager;
using eHi.Library.Common;
using FeI.Dependency;

namespace CockQuartz.Admin.Controllers
{
    public class JobManagementController : Controller
    {
        private readonly JobManagerBll _jobService;

        public JobManagementController()
        {
            _jobService = new JobManagerBll();
        }

        [HttpGet]
        public ActionResult JobList()
        {
            var groupName = ApiJobSettings.ApiJobSystemName;
            var result = _jobService.GetJobList(1, groupName);
            var instances = _jobService.GetQuartzInstances();
            ViewBag.Instances = instances;
            ViewBag.GroupName = groupName;
            return View(result);
        }
        [HttpPost]
        public ViewResult JobList(int pageIndex = 1, string groupName = "")
        {
            var result = _jobService.GetJobList(pageIndex, groupName);
            ViewBag.GroupName = groupName;
            return View("Partial/_JobList", result);
        }

        [HttpGet]
        public ActionResult JobLogList(int jobId)
        {
            var result = _jobService.GetJobLogList(jobId);
            return View(result);
        }

        //[HttpPost]
        //public JsonResult CreateJob(JobDetail job)
        //{
        //    _jobService.CreateJob(job);
        //    return Json(true);
        //}

        [HttpPost]
        public JsonResult RunJob(int id)
        {
            _jobService.RunJob(id);
            return Json(new { success = true, message = "成功" });
        }

        [HttpPost]
        public JsonResult DeleteJob(int id)
        {
            _jobService.DeleteJob(id);
            return Json(new { success = true, message = "成功" });
        }

        [HttpPost]
        public JsonResult PauseJob(int id)
        {
            _jobService.PauseJob(id);
            return Json(new { success = true, message = "成功" });
        }

        [HttpPost]
        public JsonResult StartJob(int id)
        {
            _jobService.StartJob(id);
            return Json(new { success = true, message = "成功" });
        }

        [HttpPost]
        public JsonResult ResumeJob(int id)
        {
            _jobService.ResumeJob(id);
            return Json(new { success = true, message = "成功" });
        }

        [HttpPost]
        public JsonResult ModifyJobCron(int id, string cron)
        {
            _jobService.ModifyJobCron(id, cron);
            return Json(new { success = true, message = "成功" });
        }

        [HttpPost]
        public JsonResult ModifyExceptionEmail(int id, string exceptionEmail)
        {
            _jobService.ModifyExceptionEmail(id, exceptionEmail);
            return Json(new { success = true, message = "成功" });
        }

        //[HttpPost]
        //public JsonResult ModifyRequestUrl(int id, string requestUrl)
        //{
        //    _jobService.ModifyRequestUrl(id, requestUrl);
        //    return Json(new { success = true, message = "成功" });
        //}
    }
}

CockQuartz.Admin/Controllers/TestController.cs
using System;
using System.Linq;
using System.Threading;
using System.Web.Http;
using System.Web.Services.Description;
using CockQuartz.Core.Infrastructure;
using CockQuartz.Core.JobManager;
using ServiceClients;

namespace CockQuartz.Admin.Controllers
{
    public class TestController : ApiController
    {
        private readonly JobMangerDal _jobMangerDal;
        private readonly IServiceClient _serviceClient;

        public TestController()
        {
            _jobMangerDal = new JobMangerDal();
            _serviceClient = new ServiceClient();
        }

        [Route("CheckUserSummaryError")]
        [ApiJob(
            ApiJobName = "检查用户Summary",
            ApiJobDeveloper = "xijianyao",
            ApiJobDeveloperMail = "jianyao.xi@1hai.cn",
            ApiJobDescription = "检查用户Summary描述"
            )]
        public void Get()
        {
            var a = _jobMangerDal.GetJobDetails();
            throw new Exception(a.FirstOrDefault()?.Cron);
        }

        [Route("SendRequest")]
        [ApiJob(
            ApiJobName = "请求百度接口",
            ApiJobDeveloper = "xijianyao",
            ApiJobDeveloperMail = "jianyao.xi@1hai.cn",
            ApiJobDescription = "请求百度接口描述"
        )]
        public void SendRequest()
        {
            new ServiceClient().Request("http://www.baidu.com", HttpVerb.Get, new { });
            Console.WriteLine("111");
        }

        //[Route("SendRequest1")]
        [ApiJob(
            ApiJobName = "睡眠十秒",
            ApiJobDeveloper = "xijianyao",
            ApiJobDeveloperMail = "jianyao.xi@1hai.cn",
            ApiJobDescription = "睡眠十秒"
        )]
        public void SendRequest1()
        {
            new ServiceClient().Request("http://www.baidu.com", HttpVerb.Get, new { });
            Thread.Sleep(10000);
            Console.WriteLine("111");
        }

        // POST api/<controller>
        public void Post([FromBody]string value)
        {
        }

        // PUT api/<controller>/5
        public void Put(int id, [FromBody]string value)
        {
        }

        // DELETE api/<controller>/5
        public void Delete(int id)
        {
        }

    }
}

CockQuartz.Admin/Views/JobManagement/CreateJob.cshtml
@{
    Layout = null;
}
<div class="modal-header">
    <div class="modal-title">创建Job</div>
</div>
<div class="filter-box">
    <form id="CreateJobform" class="form-horizontal">
        <div class="col-xs-6 col-md-4 col-sm-6 col-lg-6">
            <div class="form-group">
                <label class="col-xs-5 control-label">JobName：</label>
                <div class="col-xs-7">
                    <input class="form-control" placeholder="请填写JobName" id="JobName" name="JobName" type="text" />
                </div>
            </div>
        </div>
        <div class="col-xs-6 col-md-4 col-sm-6 col-lg-6">  
            <div class="form-group">
                <label class="col-xs-5 control-label">JobGroupName：</label>
                <div class="col-xs-7">
                    <input class="form-control" id="JobGroupName" readonly="readonly" name="JobGroupName" type="text" value="@ViewBag.GroupName" />
                </div>
            </div>
        </div>
        <div class="col-xs-6 col-md-4 col-sm-6 col-lg-6" style="display:none">
            <div class="form-group">
                <label class="col-xs-5 control-label">TriggerName：</label>
                <div class="col-xs-7">
                    <input class="form-control" id="TriggerName" name="TriggerName" readonly="readonly" type="text" value="@(ViewBag.GroupName+"Trigger")" />
                </div>
            </div>
        </div>
        <div class="col-xs-6 col-md-4 col-sm-6 col-lg-6" style="display:none">
            <div class="form-group">
                <label class="col-xs-5 control-label">TriggerGroupName：</label>
                <div class="col-xs-7">
                    <input class="form-control" id="TriggerGroupName" name="TriggerGroupName" readonly="readonly" type="text" value="@(ViewBag.GroupName+"TriggerGroup")" />
                </div>
            </div>
        </div>
        <div class="col-xs-6 col-md-4 col-sm-6 col-lg-6">
            <div class="form-group">
                <label class="col-xs-5 control-label">RequestUrl：</label>
                <div class="col-xs-7">
                    <input class="form-control" id="RequestUrl" name="RequestUrl" placeholder="请填写RequestUrl" type="text" />
                </div>
            </div>
        </div>
        <div class="col-xs-6 col-md-4 col-sm-6 col-lg-6">
            <div class="form-group">
                <label class="col-xs-5 control-label">Cron：</label>
                <div class="col-xs-7">
                    <input class="form-control" id="Cron" name="Cron" placeholder="请填写Cron表达式" type="text" />
                </div>
            </div>
        </div>
        <div class="col-xs-6 col-md-4 col-sm-6 col-lg-6">
            <div class="form-group">
                <label class="col-xs-5 control-label">ExceptionEmail：</label>
                <div class="col-xs-7">
                    <input class="form-control" id="ExceptionEmail" name="ExceptionEmail" placeholder="请填写ExceptionEmail" type="text" />
                </div>
            </div>
        </div>
    </form>
</div>
<div class="modal-footer">
    <button type="button" class="j-modal-cancel btn" id="modalCanel">
        <span>取消</span>
    </button>
    <button type="button" class="j-modal-ok btn btn-primary" id="modalBtnAddJob">
        <span>确定</span>
    </button>
</div>

CockQuartz.Admin/Views/JobManagement/JobList.cshtml
@using eHi.Common.Dto.Paged;
@model PagedResultDto<CockQuartz.Core.Dto.JobDetailOutputDto>

@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}



<h1 style="text-align: center">
    <strong>Job控制界面</strong>
</h1>
    @section instancename{
        <div class="dropdown">
            <button class="btn btn-hollow btn-hollow-info dropdown-toggle" type="button" aria-expanded="false">
                实例与心跳
                <span class="caret"></span>
            </button>
            <ul class="dropdown-menu">
                @foreach (dynamic item in ViewBag.Instances)
                {
                    <li>实例名：@item.InstanceName</li>
                    <li>心跳：@item.HeartBeat</li>
                }
            </ul>
        </div>
    }
<input type="hidden" id="JobGroupName" value="@(ViewBag.GroupName)"/>
<div style="width:100%; margin: 0 auto; text-align: right; height: 30px; line-height: 20px" id="divlist">
    @Html.Partial("Partial/_JobList", Model)
</div>
<div class="pull-left">
    @*<input type="button" id="btnAddJob" value="添加Job" class="btn btn-primary" />*@
</div>
<script>
    url = {
        btnRun: "@Url.Action("RunJob", "JobManagement")",
        btnStop: "@Url.Action("PauseJob", "JobManagement")",
        btnResume: "@Url.Action("ResumeJob", "JobManagement")",
        btnStart: "@Url.Action("StartJob", "JobManagement")",
        btnDelete: "@Url.Action("DeleteJob", "JobManagement")",
        btnEdit: "@Url.Action("ModifyJobCron", "JobManagement")",
        btnEditExceptionEmail: "@Url.Action("ModifyExceptionEmail", "JobManagement")",
        @*btnEditRequestUrl: "@Url.Action("ModifyRequestUrl", "JobManagement")",
        btnAddJob: "@Url.Action("CreateJob", "JobManagement")",*@
        jobList: "@Url.Action("JobList", "JobManagement")"
    }
</script>

@section modal{

    <div id="JobModal" class="modal customer-class in">
        <div class="modal-dialog">
            <div class="modal-content">
                <button type="button" class="j-modal-close modal-close"><span class="modal-close-x">×</span></button>

                <div class="modal-body">
                    <div id="addmodal">
                        @Html.Partial("CreateJob")
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="modal-backdrop"></div>
}
@section Script{
    @Scripts.Render("~/Scripts/JobManagement.js")
}

CockQuartz.Admin/Views/JobManagement/JobLogList.cshtml
@model List<CockQuartz.Model.JobExecuteLogs>
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>JobLogList</title>
</head>
<body>
    <div>
        <table>
            <thead>
                <tr>
                    <th>
                        Job名称
                    </th>
                    <th>
                        是否成功
                    </th>
                    <th>
                        信息
                    </th>
                    <th>
                        失败信息
                    </th>
                    <th>
                        时间
                    </th>
                </tr>
            </thead>
            <tbody>
                @if (Model != null && Model.Any())
                {
                    foreach (var item in Model)
                    {
                        <tr>
                            <th>
                                @item.JobName
                            </th>
                            <th>
                                @item.IsSuccess
                            </th>
                            <th>
                                @item.Message
                            </th>
                            <th>
                                @item.ExceptionMessage
                            </th>
                            <th>
                                @item.CreationTime.ToString("yyyy-MM-dd HH:mm:ss.fff")
                            </th>
                        </tr>
                    }
                }

            </tbody>
        </table>
    </div>
</body>
</html>

CockQuartz.Admin/Views/JobManagement/Partial/_JobList.cshtml
@using eHi.Common.Dto.Paged;
@model PagedResultDto<CockQuartz.Core.Dto.JobDetailOutputDto>
@{
    ViewBag.Title = "_JobList";
    Layout = null;
    var pageCount = (int)Math.Ceiling(Model.TotalCount / 10.0);
    pageCount = pageCount > 1 ? pageCount : 1;
}
<table class="table table-bordered table-bordered-hover text-center">
    <thead>
        <tr>
            <th>
                Job名称
            </th>
            <th>
                Job分组
            </th>
            <th>
                当前状态
            </th>
            <th>
                Cron表达式
            </th>
            <th>
                上次运行时间
            </th>
            <th>
                下次运行时间
            </th>
            <th>
                ExceptionEmail
            </th>
            <th>
                描述
            </th>
            <th>
                操作
            </th>
        </tr>
    </thead>
    <tbody>
        @if (Model != null && Model.Items.Any())
        {
            foreach (var item in Model.Items)
            {
                <tr>
                    <td>
                        @item.JobName
                    </td>
                    <td>
                        @item.JobGroupName
                    </td>
                    <td class="status">
                        @item.CurrentStatus
                    </td>
                    <td>
                        @item.Cron
                    </td>
                    <td>
                        @item.LastRunTime
                    </td>
                    <td>
                        @item.NextRunTime
                    </td>
                    <td>
                        @item.ExceptionEmail
                    </td>
                    <td>
                        @item.Description
                    </td>
                    <td data-jobId='@item.Id.ToString()' data-corn='@item.Cron'>

                        <div class="dropdown">
                            <button class="btn btn-hollow btn-hollow-info dropdown-toggle" type="button" aria-expanded="false">
                                更多
                                <span class="caret"></span>
                            </button>
                            <ul class="dropdown-menu">
                                <li>
                                    <a class="btnEdit" href="">修改计划</a>
                                </li>
                                <li>
                                    <a class="btnEditExceptionEmail" href="">修改ExceptionEmail</a>
                                </li>
                                @*<li>
                                        <a class="btnEditRequestUrl" href="">修改RequestUrl</a>
                                    </li>*@
                                @if (!item.IsInSchedule)
                                {
                                    <li>
                                        <a class="btnRun" href="">加入计划</a>
                                    </li>
                                }
                                @if (item.CurrentStatus == "Normal")
                                {
                                    <li>
                                        <a href="" class="btnStart">立即执行</a>
                                    </li>
                                    <li>
                                        <a href="" class="btnStop">停止</a>
                                    </li>
                                }
                                @if (item.CurrentStatus == "Paused")
                                {
                                    <li>
                                        <a href="" class="btnResume">恢复运行</a>
                                    </li>
                                }
                                <li>
                                    <a class="btnDelete" href="">删除Job</a>
                                </li>
                                @if (item.IsInSchedule)
                                {
                                    <li>
                                        <a target="_blank" href="@Url.Action("JobLogList","JobManagement",new {jobId = item.Id})"
                                           class="btnView">查看日志</a>
                                    </li>
                                }
                            </ul>
                        </div>

                    </td>
                </tr>
            }

        }

    </tbody>
</table>
<input type="hidden" id="pageCount" value="@pageCount" />
@Html.Partial("~/Views/Shared/_Page.cshtml")

CockQuartz.Admin/Views/Shared/_Layout.cshtml
@using CockQuartz.Admin.Common
<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <title>job管理</title>
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link href="@(CockQuartzConst.StaticUrl)Eui/example1.1/favicon.ico?v=@MvcApplication.Version" rel="shortcut icon" />
    <link href="@(CockQuartzConst.StaticUrl)Eui/1.1/css/eui.min.css?v=@MvcApplication.Version" rel="stylesheet" />

    <link href="~/Content/loading/loading.css" rel="stylesheet" />
    @RenderSection("Header", false)
</head>
<body>
    <div class="header clearfix">
        <div class="header-logo pull-left">
            <a class="logo" href="####">一嗨租车</a>
        </div>
        <div id="J_HeaderNav" class="header-nav pull-left">
            <h1 class="header-nav-text">Job控制界面</h1>
        </div>
        <div class="header-opt pull-right">
            <ul class="list-unstyled header-opt-list clearfix">
                <li><a href="~/CronHelp.htm" target="_blank">Cron表达式帮助</a></li>
            </ul>
            @RenderSection("instancename", false)
            @*<ul class="list-unstyled header-opt-list clearfix">

                @if (!string.IsNullOrWhiteSpace(userName) && !string.IsNullOrWhiteSpace(userId))
                 {
                     <li>欢迎您，@userName（工号：@userId）</li>
                     <li><a href="#"><i class="opt-signout"></i>退出</a></li>
                 }
                        </ul>*@
        </div>
    </div>
    <div id="J_Content" class="content">
        <!-- sidebar -->
        <div class="content-sidebar">
            <div class="sidebar-nav">

                <div class="sidebar-nav-item active">
                    <ul class="list-unstyled sidebar-nav-menu" id="selecedGroupName">
                        <li class=""><a href="@Url.Action("JobList","JobManagement")">管理页面</a></li>
                        @*<li class=""><a href="@(Url.Action("JobList","JobManagement")+"?groupName=" +"自驾后台")">自驾后台</a></li>*@

                    </ul>
                </div>



                @*@Html.Partial("~/Views/Shared/_Navigation.cshtml") 侧边栏
                *@

            </div>
            <div id="J_HideSidebarBtn" class="sidebar-btn"><span></span></div>
        </div>

        <!--更新Loading效果-->
        <div class="dw-btn btn-warning"></div>

        <!-- product -->
        <div class="content-product">
            <div class="content-product-wrapper">
                <div class="content-product-container">
                    <div class="container">
                        <div id="navigation">
                            @RenderBody()
                        </div>

                    </div>
                </div>
            </div>
        </div>

    </div>
    <script src="@(CockQuartzConst.StaticUrl)Eui/1.1/js/jquery.min.js?v=@MvcApplication.Version"></script>
    <script src="@(CockQuartzConst.StaticUrl)Eui/1.1/js/eui.min.js?v=@MvcApplication.Version"></script>

    <script src="~/Scripts/loading/loading.js"></script>
    <script src="~/Scripts/Common.js?v=@MvcApplication.Version"></script>
    <script type="text/javascript">
        $(function () {
            //用于模糊查询

            $('.js-example-basic-single').select2();
        });
    </script>
    @RenderSection("modal", false)
    @RenderSection("Script", false)

</body>
</html>